export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

// TODO - Adicionar service worker para guardar models;
// TODO - Adicionar og meta tags para seo e share

export default function VanLayout({ children }: { children: React.ReactNode }) {
  return <div className='h-screen'>{children}</div>;
}
