name: Linter

on: push

jobs:
  linter:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install eslint
        run: yarn add eslint --dev

      - name: Lint code
        run: yarn eslint src